import "@styles/tailwind.css"
import { Analytics as VercelAnalytics } from "@vercel/analytics/react"

import { TwIndicators } from "@components/index"

interface RootLayoutProps {
  children: React.ReactNode
}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>{children}</body>
      <VercelAnalytics />
      <TwIndicators />
    </html>
  )
}
