export { default as Number } from "./Number"
export { default as Connector } from "./Connector"
export { default as Title } from "./Title"
export { default as Decorator } from "./Decorator"
export { default as Text } from "./Text"
export { default as Photo } from "./Photo"
export { default as Link } from "./Link"
